name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install fonts and compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk --no-cache add msttcorefonts-installer fontconfig && update-ms-fonts && fc-cache -f
            xelatex -synctex=1 -interaction=nonstopmode main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf

      - name: Put pdf file in Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: Compiled pdf for ${{ github.sha }}
          files: |
            main.pdf

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "main.pdf"
          destination_repo: "HectorHW/diploma-releases"
          user_email: "vsredkin01@gmail.com"
          user_name: "Vladimir Redkin"
          destination_branch: "master"
